title: Abhilash Sharma # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  DevOps | Technical Architect | Full Stack Developer 
  <br><br>
  Certified Professional Scrum Master with 12+ years of Experience in Software Industry
  <br><br>
  <a href="https://www.linkedin.com/in/abhilashsharma1986/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
